### PR TITLE
Modified commit description to display question tags & difficulty level

### PR DESCRIPTION
**Pull request by pkdhirasaria**
1. Changed function parseStats to return commit message from TIme and Space information to question tags and difficult level of question.

Commit message will change form 

**Time: 1724 ms (5.13%), Space: 37.8 MB (98.68%) - LeetHub**
TO 
**[ Backtracking, Tree, Depth-First Search, Binary Tree ] Medium**
Screenshot 2021-12-31 at 12 46 25 PM

### CODE REVIEW

**Comment by QasimWani** [comment]
It makes more sense to have a table of difficulty and other problem stats. LeetHub's time and space complexity make more sense the way it is. As mentioned previously #114, having a table would be more intuitive. 
Please open a new PR if you're working in that direction.

**Comment by kaustav202** [comment]
Has the functionality been integrated @pkdhirasaria @QasimWani

**Comment by pkdhirasaria** [comment]
> Has the functionality been integrated @pkdhirasaria @QasimWani

It was decided that this is a user-specific request and more generally will be to have time and space complexity as a commit message, if you want to have this feature then you can pull my changes and use a modified version

**Comment by kaustav202** [comment]
> > Has the functionality been integrated @pkdhirasaria @QasimWani
> 
> It was decided that this is a user-specific request and more generally will be to have time and space complexity as a commit message, if you want to have this feature then you can pull my changes and use a modified version 

Yes I noticed that in your repo @pkdhirasaria 
I find it a much better alternative, would be great can you help me with it.. how to set it up since it's a chrome extension.

Also I think if it can be added as an option in the extension itself in future that'd be a nice addition!

**Pull request closed without merging**
