### PR TITLE
Firefox compatbility

### PR DESCRIPTION
**Pull request by njelich**
This is a pull request to add firefox compatibility to the extension.

This patch does not break compatibility with chrome (though further testing is recommended)

Solves #3

### CODE REVIEW

**Comment by festus14** [comment]
Is it compatible on Firefox now?

**Comment by njelich** [comment]
Yes, should be. Why wasn't this merged?

**Comment by festus14** [comment]
> Yes, should be. Why wasn't this merged?

It will be really nice if its merged and made available on firefox store

**Comment by njelich** [comment]
@QasimWani Please merge this dude.

**Comment by SamKomesarook** [comment]
Bumping this, would be awesome to have on Firefox

**Comment by festus14** [comment]
@njelich there seems to be a conflict. You can check it out if you are chanced. Thanks

**Comment by njelich** [comment]
Resolved the merge. Please merge this now, its been over half a year @QasimWani

**Comment by TheSpeedForce** [comment]
How do I install this?

**Pull request merged**
